### PR TITLE
add some Sysinfo

### PR DESCRIPTION
**Pull request by DanielR92**
first draft to display on the page. Is it important to add it in the mqtt too?

### CODE REVIEW

**Comment by DanielR92** [comment]
Can sombedoy test it with ESP8266?

**Comment by DanielR92** [comment]
@lumapu weist du warum lumapu:main into dev03 ist?

**Comment by DanielR92** [comment]
some wired stuff with main into...

**Comment by lumapu** [comment]
@DanielR92 kann nichts von main sehen

**Pull request closed without merging**
