### PR TITLE
Revisions made to eep.h for updating library and respective methods

### PR DESCRIPTION
**Pull request by Nini12345678901**
Changes have been made to replace the EEPROM library with Preferences.h as well as their respective functions for read and write. The revisions are then committed to the Preferences library.

### CODE REVIEW

**Comment by stefan123t** [comment]
@Nini12345678901 Sajani, thanks for providing the Preferences.h update to eep.h
IMHO this is only available for the ESP32 platform under https://github.com/espressif/arduino-esp32/tree/master/libraries/Preferences
For the ESP8266 platform this has to remain based on the EEPROM Library https://github.com/esp8266/Arduino/tree/master/libraries/EEPROM

@lumapu what is your intention on how to merge this PR.
We could either create two libraries eep.h and prefs.h or keep it inside eep.h with #ifdef's for ESP8266 and ESP32 ?

**Comment by lumapu** [comment]
I prefer one file. Should be more clean and the stuff for all MCUs can share at least a few lines of code

**Comment by stefan123t** [comment]
@Nini12345678901 how would you like to continue:
a) Update this PR to fix the ESP8266 build OR
b) Create a new PR to include the changes for ESP32 and #ifdefs for ESP8266

**Comment by Nini12345678901** [comment]
Sorry for the late reply, I think updating would be better. Although some parts seemed to work better using the prefs library, there are still some issues present that require further attention.

**Comment by stefan123t** [comment]
@Nini12345678901 thanks for coming back. I have tried to patch my version with the changes you proposed and at least there was at least an instance `Preferences prefs;` missing. I also added the Preferences.h as a lib_deps dependency to the platformio.ini's esp32 envs.
In general this should have worked somehow but I still got a plenty of Warnings/Errors.

Though I think this can be postponed until we have a proper LittleFS / SPIFFS to store the prefs.

I got the ESP32 build to work with just two flags as suggested by homeautomation via Discord:
`build_flags = -std=c++14` and `build_unflags = -std=gnu++11`


```c
[env:esp32-wroom32-release]
platform = espressif32
board = lolin_d32
build_flags =  -std=gnu++14 -D RELEASE
build_unflags = -std=gnu++11
lib_deps =     ${env.lib_deps}
            https://github.com/me-no-dev/ESPAsyncWebServer.git
            me-no-dev/AsyncTCP@^1.1.1
monitor_filters = 
    ;default   ; Remove typical terminal control codes from input
    time      ; Add timestamp with milliseconds for each new line
    ;log2file  ; Log data to a file “platformio-device-monitor-*.log” located in the current working directory

[env:esp32-wroom32-debug]
platform = espressif32
board = lolin_d32
build_flags = -std=gnu++14 -DDEBUG_LEVEL=DBG_DEBUG -DDEBUG_ESP_CORE -DDEBUG_ESP_WIFI -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DDEBUG_ESP_OOM -DDEBUG_ESP_PORT=Serial
build_unflags = -std=gnu++11
build_type = debug
lib_deps =     ${env.lib_deps}
            https://github.com/me-no-dev/ESPAsyncWebServer.git
            me-no-dev/AsyncTCP@^1.1.1
monitor_filters = 
    ;default   ; Remove typical terminal control codes from input
    time      ; Add timestamp with milliseconds for each new line
    log2file  ; Log data to a file “platformio-device-monitor-*.log” located in the current working directory
```

**Comment by lumapu** [comment]
@Nini12345678901 @stefan123t what is the state of this PR?

**Comment by stefan123t** [comment]
@lumapu I do not know if we currently need to switch from plain EEPROM with our own memory layout to the newer ESP32 variant Preferences.h given your usual suspicion about libraries. But then again it seems to be the preferred way of storing such information in the Espressif / Arduino way.
@Nini12345678901 anyway this needs some loving touches as it did not work as is and I could not bring it to life when I tried the PR.

**Comment by lumapu** [comment]
closed because of littlefs implementation

**Pull request closed without merging**
