### PR TITLE
Add in setup site Debug_Lvl (not work) & add Disclaimer

### PR DESCRIPTION
**Pull request by DanielR92**
Attention: Disclaimer will popup and will only close when the user type 'YeS'.
In normal mode it dont show.

### CODE REVIEW

**Comment by DanielR92** [comment]
Need help to integrate the variable into the eeprom to save it for the next start.
And important, to check all debug messages to handle it with the value.

**Comment by stefan123t** [comment]
Hi @DanielR92 
the EEPROM structure is in defines.h that needs to be extended to include a global value (boolean) for the disclaimer.
Next eep.c/include/eep.h need to be extended to store/restore the mDisclaimer in EEPROM.

**Comment by DanielR92** [comment]
Please do not make a Pull, I had to make some other changes and its not done yet. :)

**Comment by DanielR92** [comment]
Disclaimer PR is out: https://github.com/lumapu/ahoy/pull/333
Debug Level needs more effort.

**Pull request closed without merging**
